version: 2

# Specify the build environment
build:
  os: ubuntu-22.04
  tools:
    python: 3.9  # Adjust to match your package's Python version

# Sphinx configuration
sphinx:
  configuration: docs/conf.py  # Path to your conf.py file

# Python dependencies
python:
  install:
    - requirements: docs/requirements.yaml  # Ensures dependencies are installed

# Enable automatic API documentation generation (if using `sphinx-apidoc`)
build.commands:
  - sphinx-apidoc -o docs/source path/to/your/package --force
  - make html  # Or sphinx-build -b html docs/source docs/build

# Optional: Define explicit submodules if using Git submodules
submodules:
  include: true

# Optional: Custom build settings
formats: ["htmlzip", "pdf", "epub"]

# Enable MkDocs if using it alongside Sphinx
# mkdocs:
#   configuration: mkdocs.yml

