name: docs
channels:
  - conda-forge
dependencies:
  # Base depends
  - python>=3.10
  - pip>=19.0

  # Package and docs dependencies
  - numpy>=2.0
  - matplotlib
  - scipy
  - sphinx
  - sphinx_rtd_theme

  # Pip-only installs
  - pip:
    - sphinx-autoapi
